module.exports={
    USER_COLLECTION:'userdetails',
    PRODUCT_COLLECTION:'products',
    CART_COLLECTION:'cart',
    ORDER_COLLECTIONS:'order',
    COUPON_COLLECTIONS:'coupon',
    ADDRESS_COLLECTIONS:'address', 
    OFFERS_COLLECTIONS:'offers'
}